env: local
budget_guard:
  daily_usd: 3.00
  soft_stop_pct: 85
providers:
  - name: openai
    models: ["gpt-4o-mini", "gpt-4.1-mini"]
    max_rps: 2
fallbacks:
  order: ["openai:gpt-4o-mini", "openai:gpt-4.1-mini"]
circuit_breaker:
  error_rate_threshold: 0.25
  rolling_seconds: 60
